### PR TITLE
fixes behav in singl-session-subjects in long study

### PR DESCRIPTION
**Pull request by fliem**
This is the revived PR #22.
In longitudinal studies (studies in which at least one subject has more than one session) and --multiple_sessions='longitudinal') subjects with only one session should undergo the entire longitudinal stream. The changes in #11 broke that behavior. The present changes should fix it.

- The longitudinal check was moved to the top, as it needs to loop through all subjects and look for sessions, before running the `recon-all` commands in a second loop.
- At the moment longitudinal test cases cannot be run as they take >2h (#23).
- I've made the test1 check for a recon-all.done file after it is done.

### CODE REVIEW

**Comment by alexlicohen** [comment]
The run.py code change looks like it would reset `longitudinal_study ` which each subject it checks, thus would be set by how many sessions the last subject has, vs the if any of the subjects had multiple sessions.

**Comment by fliem** [comment]
Thanks. I reverted to my very first implementation that searches for the first multi-sessions subject and stops if it is found. I've also added a `multi_session_study` variable to make things clearer.

**Comment by alexlicohen** [comment]
That looks right... you could also just set longitudinal_study to False
above the loop, then break when set to True on line 100, without an
additional variable and drop the else conditional on line 105


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by fliem** [comment]
My thinking was that it might not hurt to have this variable for later.

**Pull request merged**
