### PR TITLE
Resolves Issue #5

### PR DESCRIPTION
**Pull request by alexlicohen**
Added options for using T2 OR FLAIR images for pial refinement. The default is now to not use either, instead of automatically trying to use the T2s. (If this is not desired, then a resolution check for appropriateness should be added).

### CODE REVIEW

**Comment by chrisgorgo** [comment]
This is a very much appreciated addition, but I would like to discuss the proposed choice of defaults. Ideally I would prefer the app to run the best analysis given the included data with minimal user intervention. Are you proposing not to use T2/FLAIR images by default because:
a) FreeSurfer does not benefit from them in most cases
or
b) they need to be of a certain resolution for the analysis to work correctly

If it's b) I would prefer to check the resolution of discovered T2/FLAIR files and include them if they are detailed enough. A flag could force inclusion of T2/FLAIR independently of their resolution. WDYT?

**Comment by alexlicohen** [comment]
It's the second case. The T2 or FLAIR (MGH prefers to use SPACE T2 FLAIR
sequences over SPACE T2) need to be 1x1x1mm to be of benefit. I would be
reluctant to have using the T2 be the default unless a resolution check is
in place (and that's beyond my skills at present).

If you can add that (I'd put an max of 1.2mm in any plane as a cap) then
defaulting to using T2, elif to FLAIR (also with a resolution check) would
most likely be a 'best handsfree' default.

(I would not suggest adding a force T2/FLAIR switch as it may confuse
people who don't understand the need for a '3D' / 1x1x1 T2, not just any
T2...)

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by chrisgorgo** [comment]
This check should be easy to implement. Try this:

```
import nibabel
max(nibabel.load(path_to_nifti_file).header.get_zooms()) < 1.2
```

You might need to add the following lines to Dockerfile to get nibabel installed:

```
RUN apt-get install -y python3-pip
RUN pip3 install nibabel
```

**Comment by chrisgorgo** [comment]
Thanks for taking the extra mile adding the resolution checks. Is this PR ready for review now or are you still working on it?

**Comment by alexlicohen** [comment]
Ready for review. Thanks for the python pointers!

-Alex

**Comment by chrisgorgo** [comment]
The way this is implemented now works well if the dataset includes T2s with appropriate resolution and user wants to use them. It's a bit more problematic when:
1) user does not want T2s to be used (what should be the flag?)
2) user wants to ignore the resolution checks and use T2s nontheless (Q: is this a sensible usecase?)

If only 1) is a sensible use case I would suggest adding "None" to `--refine_pial` choices. If 2) is also of a a concern I would add a `--ignore_refine_pial_res_checks`.

**Comment by alexlicohen** [comment]
1) This goes back to my concern that someone used to using freesurfer is
going to assume it will only use the T1s unless you specify a T2pial or
FLAIRpial flag...

A None or T1only flag could be added to perform the typical freesurfer
pipeline, but which do you want to be the default: "hands-off use
everything?" or "replicate the typical freesurfer pipeline"

2) should be strongly discouraged.

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by chrisgorgo** [comment]
Ok let's just add "None" and keep the current defaults. Thanks!

**Comment by alexlicohen** [comment]
Failed Travis CI b/c it took 'too long'... It looks like it's actually working though.

**Comment by chrisgorgo** [comment]
Thanks!

**Pull request merged**
