### PR TITLE
Resolves Issue #7: rmtree now based on "IsRunning"

### PR DESCRIPTION
**Pull request by alexlicohen**

### CODE REVIEW

**Comment by alexlicohen** [comment]
Chris, this should be ready for review.

**Comment by chrisgorgo** [comment]
Have you tested this? I'm getting the following error

```
filo@MSI MINGW64 /d/drive/workspace/freesurfer (patch-2)
$ docker run --rm -ti -v //d/scratch/freesurfer://out -v //d/data/ds009_R2.0.1://in bids/freesurfer:isrunning in out participant --participant_label 01 --license_key jskdfhkjsd
        1: Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
                /sub-01/func/sub-01_task-balloonanalogrisktask_bold.nii.gz
                /sub-02/func/sub-02_task-balloonanalogrisktask_bold.nii.gz
                /sub-03/func/sub-03_task-balloonanalogrisktask_bold.nii.gz
                /sub-04/func/sub-04_task-balloonanalogrisktask_bold.nii.gz
                /sub-05/dwi/sub-05_dwi.nii.gz
                /sub-06/func/sub-06_task-balloonanalogrisktask_bold.nii.gz
                /sub-07/func/sub-07_task-balloonanalogrisktask_bold.nii.gz
                /sub-09/func/sub-09_task-balloonanalogrisktask_bold.nii.gz
                /sub-10/func/sub-10_task-balloonanalogrisktask_bold.nii.gz
                /sub-11/func/sub-11_task-balloonanalogrisktask_bold.nii.gz
                ... and 14 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:                Available Modalities:
        855 Files, 6.07GB        stop signal                     T1w
        24 - Subjects            emotional regulation            inplaneT2
        1 - Session              discounting                     dwi
                                 balloon analog risk task        bold


recon-all -subjid sub-01 -sd /out -i in/sub-01/anat/sub-01_T1w.nii.gz -autorecon-all -openmp 1
ERROR: You are trying to re-run an existing subject with (possibly)
 new input data (-i). If this is truly new input data, you should delete
 the subject folder and re-run, or specify a different subject name.
 If you are just continuing an analysis of an existing subject, then
 omit all -i flags.

Traceback (most recent call last):
  File "/code/run.py", line 220, in <module>
    run(cmd)
  File "/code/run.py", line 24, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1
```

It seems that the file indicating that the piepeline is running is `IsRunning.lh+rh` not `IsRunning`


```
filo@MSI MINGW64 /d/drive/workspace/freesurfer (patch-2)
$ ls /d/scratch/freesurfer/sub-01/scripts/
build-stamp.txt  csurfdir  IsRunning.lh+rh  recon-all.cmd  recon-all.env  recon-all.local-copy*  recon-all.log  recon-all-status.log
```

**Comment by alexlicohen** [comment]
Ack, you're right... Let me run some further tests...

-Alex

**Comment by alexlicohen** [comment]
Ok, working for me locally.

**Pull request merged**
