### PR TITLE
Update to FreeSurfer 6.0.0

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by alexlicohen** [comment]
To do list:
- [x] add the `-parallel` flag right before `-openmp`, per: [https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes6.0](url)

- [x] FS6 no longer needs FSL for `bbregister `, this may remove the dependency for pial improvement as well.

- [x] Consider adding a `-hires` flag with additional checks for sub <1mm data or the converse, if <1mm data is provided, turn on the hires flag...

- [ ]  With some of the new processing modes, e.g., hippocampal subfields, etc... it might be worth adding the ability to directly pass-through arguments from the docker call to FS... this is probably a bigger task than worthwhile for now, but would remove some of the necessity of custom coding each additional option.

**Comment by chrisgorgo** [comment]
Thanks for the comments. I resolved the first two suggestions and created issues for the other two.

**Comment by alexlicohen** [comment]
What does this new line in the Dockerfile do?
`RUN echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IC9vcHQvZnJlZXN1cmZlci9saWNlbnNlLnR4dAo=" | base64 -d | sh`

**Comment by chrisgorgo** [comment]
It's to deal with a new way FS is evaluating the license. BTW if you know a good way to check FS license without the need to copy it to $FREESURFER_HOME (which would be read only after converting the container image to Singularity) I'm all ears!

**Comment by alexlicohen** [comment]
Hmm... I wonder if a symbolic link created in Dockerfile and pointing to a
file in the output/subjects_dir created during run.py with the contents
from would work...

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by alexlicohen** [comment]
For the licence file with singularity, have you tried this: 

> With the exception of your home directory, which is mounted from the local filesystem, the filesystem in Singularity containers is read-only. Files can be easily transferred in and out of the container by mapping local directories to directories inside the container using the -B from:to command line argument, where the from dir is mapped to to. When using mapped directories, remember that the paths specified on the command line are in relation to the directory inside the container (e.g. the to directory).

**Comment by chrisgorgo** [comment]
Yes - we are able to write to certain folders with singularity (without it
we would not be able to produce results). However, since freesurfer always
looks for the license file in $FREESURFER_HOME, we would have to copy all
of freesurfer to an output directory, and create a license file there to
make it work.

Linking would also not solve the situation, since we would have to know in
advance (when building the image) where to link to.

On Thu, Feb 2, 2017 at 3:08 PM, Alexander Li Cohen <notifications@github.com

**Comment by alexlicohen** [comment]
Can't we just 'require' that a license.txt file be in the output dir, then
we could create a link prior to singularity creation?

-Alex

----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by chrisgorgo** [comment]
We don't know what is the path of the user specified output_dir when we are
creating the image.

On Thu, Feb 2, 2017 at 3:55 PM, Alexander Li Cohen <notifications@github.com
> wrote:

> Can't we just 'require' that a license.txt file be in the output dir, then
> we could create a link prior to singularity creation?
>
> -Alex
>
> ----------------------------------------------------------------
> Alexander Li Cohen, M.D., Ph.D.
> E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
> E-mail: alexcohen@gmail.com (Lifetime Email)
> ----------------------------------------------------------------
>
> On Thu, Feb 2, 2017 at 3:19 PM, Chris Filo Gorgolewski <

**Comment by alexlicohen** [comment]
I haven't played with it, but I would have thought that the docker and/or
singularity filesystems would just see it as /output, is that not correct?

so in the Dockerfile we create a temp /output dir and put a license file
there, create a symbolic link to the freesurfer_home, then when the user
mounts a dir to /output, their license file is present (and for the docker
BIDS-App, we could add a switch that if not present, and/or if specified
with --license, the first thing it does is create it in freesurfer_home...

alternatively, -B /host-fs-license-dir:/guest-fs-license-dir
where we set up the guest dir and a symlink in the dockerfile?

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by chrisgorgo** [comment]
Yes if we could assume/force all users to always mount a host folder to
/outputs this could work. However, many Singularity systems do not allow
users to mount arbitrary folders for security reasons. They are only
allowed to access files through predefined (and auto mounted) folders such
as /scratch /home etc.

On Thu, Feb 2, 2017 at 4:41 PM, Alexander Li Cohen <notifications@github.com
> wrote:

> I haven't played with it, but I would have thought that the docker and/or
> singularity filesystems would just see it as /output, is that not correct?
>
> so in the Dockerfile we create a temp /output dir and put a license file
> there, create a symbolic link to the freesurfer_home, then when the user
> mounts a dir to /output, their license file is present (and for the docker
> BIDS-App, we could add a switch that if not present, and/or if specified
> with --license, the first thing it does is create it in freesurfer_home...
>
> alternatively, -B /host-fs-license-dir:/guest-fs-license-dir
> where we set up the guest dir and a symlink in the dockerfile?
>
> -Alex
>
>
> ----------------------------------------------------------------
> Alexander Li Cohen, M.D., Ph.D.
> E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
> E-mail: alexcohen@gmail.com (Lifetime Email)
> ----------------------------------------------------------------
>
> On Thu, Feb 2, 2017 at 4:20 PM, Chris Filo Gorgolewski <
>

**Comment by alexlicohen** [comment]
Gotcha... I'll keep thinking...

-Alex

**Pull request merged**
